// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddressRow: typeof import('./src/components/address/address-row.vue')['default']
    CartIcon: typeof import('./src/components/cart/cart-icon.vue')['default']
    CartNumberInput: typeof import('./src/components/cart/cart-number-input.vue')['default']
    CouponRow: typeof import('./src/components/coupon/coupon-row.vue')['default']
    DictColumn: typeof import('./src/components/dict/dict-column.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutUploader: typeof import('@nutui/nutui-taro')['Uploader']
    OrderRow: typeof import('./src/components/order/order-row.vue')['default']
    PopupPicker: typeof import('./src/components/popup-picker/popup-picker.vue')['default']
    ProductCategory: typeof import('./src/components/product/product-category.vue')['default']
    ProductCover: typeof import('./src/components/product/product-cover.vue')['default']
    ProductDialog: typeof import('./src/components/product/product-dialog.vue')['default']
    ProductPrice: typeof import('./src/components/product/product-price.vue')['default']
    ProductRow: typeof import('./src/components/product/product-row.vue')['default']
    ProductSkuDialog: typeof import('./src/components/product/product-sku-dialog.vue')['default']
    RegisterPopup: typeof import('./src/components/register-popup/register-popup.vue')['default']
    UserAvatar: typeof import('./src/components/user/user-avatar.vue')['default']
    UserRow: typeof import('./src/components/user/user-row.vue')['default']
    WalterFall: typeof import('./src/components/walter-fall/walter-fall.vue')['default']
  }
}
