/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutNoticebar: typeof import('@nutui/nutui-taro')['Noticebar']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    ProductCategory: typeof import('./src/components/product/product-category.vue')['default']
    ProductCover: typeof import('./src/components/product/product-cover.vue')['default']
    ProductDialog: typeof import('./src/components/product/product-dialog.vue')['default']
    ProductRow: typeof import('./src/components/product/product-row.vue')['default']
    ProductSkuDialog: typeof import('./src/components/product/product-sku-dialog.vue')['default']
    RegisterPopup: typeof import('./src/components/register-popup/register-popup.vue')['default']
    UserAvatar: typeof import('./src/components/user/user-avatar.vue')['default']
    UserRow: typeof import('./src/components/user/user-row.vue')['default']
    WalterFall: typeof import('./src/components/walter-fall/walter-fall.vue')['default']
  }
}
